### PR TITLE
[ADMIN] update license file and legal disclaimer based on LF legal

### PR DESCRIPTION
**Pull request by jpradocueva**
LF legal team has suggested to implement the following changes to the License in this repo.

Combine in one repository LICENSE.txt:

the spec's copyright statement + disclaimer language
the spec's patent licensing mode with a URL to the corresponding Working Group Charter
the applicable license for any source code

Update the legal disclaimer inside acknowledgements:
Same as it is now, the new proposal includes the corrected legal entity name for the copyright notice as well as referring to contributors.

@PickiHH  we can have a discussion about the content of this PR on our chairs meeting. I am providing the same changes to IoT Conn and SDS whitepapers.

### CODE REVIEW

**Comment by wrichter** [comment]
Looks good to me!

**Review by wrichter — APPROVED** [review]
Looks good to me!

**Review by wrichter — APPROVED** [review]

**Comment by PickiHH** [comment]
fine for me.

**Review by PickiHH — APPROVED** [review]
Fine for me.

**Pull request merged**
